export const FETCH_NEW_MOVIE = 'FETCH_NEW_MOVIE';
export const FETCH_DETAIL_MOVIE = 'FETCH_DETAIL_MOVIE';
export const FETCH_CAST_LIST = 'FETCH_CAST_LIST';
export const FETCH_STARSHIP_LIST = 'FETCH_STARSHIP_LIST';

